#!/bin/bash
# Syncthing installer functions

# --- Syncthing ---

check_syncthing() { _check_standard syncthing syncthing ""; }

install_syncthing() {
    echo "Installing Syncthing..."
    ensure_tools
    case "$DISTRO_FAMILY" in
        debian)
            _add_apt_repo \
                "https://syncthing.net/release-key.gpg" \
                "/etc/apt/keyrings/syncthing-archive-keyring.gpg" \
                "deb [signed-by=/etc/apt/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable" \
                "/etc/apt/sources.list.d/syncthing.list"
            sudo apt install -y syncthing
            ;;
        fedora)
            # Syncthing is included in official Fedora repos by default
            sudo "$PKG_MGR" install -y syncthing
            ;;
        rhel)
            # Syncthing is in EPEL, not the base RHEL/Alma/Rocky repos
            sudo "$PKG_MGR" install -y epel-release 2>/dev/null || true
            sudo "$PKG_MGR" install -y syncthing
            ;;
        arch)
            # Syncthing is available in the community repository
            sudo pacman -S --noconfirm syncthing
            ;;
        suse)
            # Install from official repository
            sudo zypper install -y syncthing
            ;;
    esac

    # Enable and start the user service (all distros)
    systemctl --user enable syncthing.service
    systemctl --user start syncthing.service

    echo ""
    echo "Syncthing installed successfully!"
    echo "Service has been enabled and started."
    echo "Access the web GUI at: http://127.0.0.1:8384"
    echo ""

    setup_syncthing_folders
}

uninstall_syncthing() {
    echo "Uninstalling Syncthing..."

    # Stop and disable the service if running
    systemctl --user stop syncthing.service 2>/dev/null || true
    systemctl --user disable syncthing.service 2>/dev/null || true

    case "$DISTRO_FAMILY" in
        debian)
            sudo apt purge --autoremove -y syncthing
            sudo apt autoclean
            sudo rm -f /etc/apt/sources.list.d/syncthing.list
            sudo rm -f /etc/apt/keyrings/syncthing-archive-keyring.gpg
            ;;
        fedora|rhel)
            sudo "$PKG_MGR" remove -y syncthing
            sudo rm -f /etc/yum.repos.d/syncthing.repo
            ;;
        arch)
            sudo pacman -Rs --noconfirm syncthing
            ;;
        suse)
            sudo zypper remove -y syncthing
            ;;
    esac
    rm -rf ~/.config/syncthing
    rm -rf ~/.syncthing
    echo "Syncthing has been uninstalled."
}

update_syncthing() {
    echo "Updating Syncthing..."
    case "$DISTRO_FAMILY" in
        debian)
            sudo apt update
            sudo apt upgrade -y syncthing
            ;;
        fedora|rhel)
            sudo "$PKG_MGR" upgrade -y syncthing
            ;;
        arch)
            sudo pacman -S --noconfirm syncthing
            ;;
        suse)
            sudo zypper update -y syncthing
            ;;
    esac
}

get_version_syncthing() {
    _ver_from_cmd syncthing || echo ""
}

# ─────────────────────────────────────────────────────────────────────────────
# Syncthing Folder Setup Wizard
# ─────────────────────────────────────────────────────────────────────────────

# Write a .stignore file at the given path using the chosen style.
# Args: path style ("permissive"|"restrictive")
_st_write_stignore() {
    local folder="$1" style="$2"
    local target="${folder}/.stignore"

    if [[ -f "$target" ]]; then
        info "  .stignore already exists at ${target} — skipping."
        return 0
    fi

    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        info "  [Dry run] Would write ${style} .stignore to ${target}"
        return 0
    fi

    if [[ "$style" == "restrictive" ]]; then
        cat > "$target" <<'EOF'
// Restrictive .stignore — generated by linux_util
// Cache and temp files
(?d).cache
(?d)__pycache__
(?d).pytest_cache
(?d)node_modules
(?d).git
*.tmp
*.swp
*.swo
*~
.DS_Store
Thumbs.db
EOF
    else
        cat > "$target" <<'EOF'
// Permissive .stignore — generated by linux_util
// Add patterns here to exclude files from sync.
// Example: *.tmp
EOF
    fi
    info "  Wrote ${style} .stignore to ${target}"
}

# Print the dotfiles guidance block.
_st_dotfiles_info() {
    {
        printf '\n'
        printf '  %s─── Dotfiles Best Practice ─────────────────────────────────────────%s\n' \
            "${BOLD:-}" "${RESET:-}"
        printf '\n'
        printf '  Keep dotfiles in a dedicated folder, e.g.  ~/dotfiles\n'
        printf '  Then use a tool to symlink them into place:\n'
        printf '\n'
        printf '    GNU Stow:  stow -v -d ~/dotfiles -t ~ bash vim git\n'
        printf '    chezmoi:   chezmoi init && chezmoi apply\n'
        printf '\n'
        printf '  This keeps synced data cleanly separated from live config files.\n'
        printf '  Do NOT sync ~/.config or ~/.local directly — those dirs contain\n'
        printf '  socket files and databases that corrupt when synced while active.\n'
        printf '\n'
    } > /dev/tty
}

# ── Main wizard ───────────────────────────────────────────────────────────────

setup_syncthing_folders() {
    {
        printf '\n'
        printf '%s%s════════════════════════════════════════════════════════════════%s\n' \
            "${BOLD:-}" "${CYAN:-}" "${RESET:-}"
        printf '%s%s  Configure Syncthing Folders                                  %s\n' \
            "${BOLD:-}" "${CYAN:-}" "${RESET:-}"
        printf '%s%s════════════════════════════════════════════════════════════════%s\n' \
            "${BOLD:-}" "${CYAN:-}" "${RESET:-}"
        printf '\n'
        printf '  This wizard helps you choose which folders to sync following\n'
        printf '  Linux best practices. Every choice is yours — nothing is changed\n'
        printf '  without your confirmation.\n'
        printf '\n'
    } > /dev/tty

    # ── Step 1: Check service ─────────────────────────────────────────────────
    if ! systemctl --user is-active --quiet syncthing.service 2>/dev/null; then
        warn "The Syncthing user service is not running."
        local start_svc
        read -rp "Start it now? [y/N]: " start_svc < /dev/tty
        if [[ "${start_svc,,}" == "y" ]]; then
            systemctl --user start syncthing.service
            info "Syncthing service started."
        else
            info "You can start it later with:  systemctl --user start syncthing.service"
            info "Continuing with folder configuration..."
        fi
    else
        info "Syncthing service is running."
    fi

    # ── Step 2: Strategy choice ───────────────────────────────────────────────
    {
        printf '\n'
        printf '  Choose a sync strategy:\n\n'
        printf '  1)  Sync specific subdirectories of ~  (recommended)\n'
        printf '      e.g. ~/Documents, ~/Projects, ~/Pictures\n\n'
        printf '  2)  Sync a dedicated data folder\n'
        printf '      e.g. ~/Data or /mnt/data — ideal for distro-hopping\n\n'
        printf '  3)  Configure manually — open web GUI and exit\n\n'
        printf '  0)  Cancel\n\n'
    } > /dev/tty

    local strategy
    while true; do
        read -rp "Select strategy [0-3]: " strategy < /dev/tty
        case "$strategy" in
            0) info "Wizard cancelled."; return 0 ;;
            1|2|3) break ;;
            *) printf '%sInvalid selection. Enter 0, 1, 2, or 3.%s\n' \
                "${RED:-}" "${RESET:-}" > /dev/tty ;;
        esac
    done

    if [[ "$strategy" == "3" ]]; then
        info "Open the web GUI to configure folders manually: http://127.0.0.1:8384"
        return 0
    fi

    # ── Step 3a: Strategy 1 — pick subdirectories ─────────────────────────────
    local -a selected_folders=()

    if [[ "$strategy" == "1" ]]; then
        local -a candidates=()
        local -a candidate_dirs=(Documents Pictures Videos Music Downloads Projects)
        local idx=0
        {
            printf '\n'
            printf '  Select directories to sync (comma-separated numbers, e.g. 1,3,5):\n\n'
        } > /dev/tty

        for dir in "${candidate_dirs[@]}"; do
            local full_path="$HOME/$dir"
            if [[ -d "$full_path" ]]; then
                (( idx++ )) || true
                candidates+=("$full_path")
                printf '  %-3s %s\n' "${idx})" "$full_path" > /dev/tty
            fi
        done
        (( idx++ )) || true
        printf '  %-3s %s\n' "${idx})" "Custom path..." > /dev/tty
        local custom_idx=$idx
        printf '\n  0)  Cancel\n\n' > /dev/tty

        if (( ${#candidates[@]} == 0 )) && (( custom_idx == 1 )); then
            info "No standard subdirectories found under ${HOME}."
        fi

        local raw_choice
        while true; do
            read -rp "Selection [0-${custom_idx}]: " raw_choice < /dev/tty
            [[ "$raw_choice" == "0" ]] && { info "Wizard cancelled."; return 0; }

            local valid=true
            IFS=',' read -ra picks <<< "$raw_choice"
            local -a resolved=()
            for pick in "${picks[@]}"; do
                pick="${pick// /}"
                if [[ ! "$pick" =~ ^[0-9]+$ ]] || (( pick < 1 || pick > custom_idx )); then
                    printf '%sInvalid number: %s%s\n' "${RED:-}" "$pick" "${RESET:-}" > /dev/tty
                    valid=false
                    break
                fi
                if (( pick == custom_idx )); then
                    resolved+=("__custom__")
                else
                    resolved+=("${candidates[$((pick - 1))]}")
                fi
            done
            [[ "$valid" == "false" ]] && continue
            (( ${#resolved[@]} == 0 )) && {
                printf '%sPlease select at least one option.%s\n' "${RED:-}" "${RESET:-}" > /dev/tty
                continue
            }
            break
        done

        for item in "${resolved[@]}"; do
            if [[ "$item" == "__custom__" ]]; then
                local custom_path
                while true; do
                    read -rp "Enter custom path (absolute): " custom_path < /dev/tty
                    [[ "$custom_path" == /* ]] && break
                    printf '%sPath must be absolute (start with /).%s\n' \
                        "${RED:-}" "${RESET:-}" > /dev/tty
                done
                selected_folders+=("$custom_path")
            else
                selected_folders+=("$item")
            fi
        done

    # ── Step 3b: Strategy 2 — dedicated data folder ───────────────────────────
    else
        local default_data="$HOME/Data"
        {
            printf '\n'
            printf '  Enter the path for your dedicated data folder.\n'
            printf '  Press ENTER to use the default: %s\n\n' "$default_data"
        } > /dev/tty

        local data_folder
        while true; do
            read -rp "Data folder [default: ${default_data}]: " data_folder < /dev/tty
            [[ -z "$data_folder" ]] && data_folder="$default_data"
            [[ "$data_folder" == /* ]] && break
            printf '%sPath must be absolute (start with /).%s\n' \
                "${RED:-}" "${RESET:-}" > /dev/tty
        done

        # Record whether we need to create the data folder (decision only — no mkdir yet)
        local create_data_folder=false
        if [[ ! -d "$data_folder" ]]; then
            local mk_confirm
            read -rp "  Directory does not exist. Create it? [y/N]: " mk_confirm < /dev/tty
            [[ "${mk_confirm,,}" == "y" ]] && create_data_folder=true
        fi
        selected_folders+=("$data_folder")

        # Parse comma/range selection into a list of indices
        _st_parse_selection() {
            local raw="$1" max="$2"
            local -a out=()
            IFS=',' read -ra parts <<< "$raw"
            for part in "${parts[@]}"; do
                part="${part// /}"
                if [[ "$part" =~ ^([0-9]+)-([0-9]+)$ ]]; then
                    local lo="${BASH_REMATCH[1]}" hi="${BASH_REMATCH[2]}"
                    for (( n=lo; n<=hi && n<=max; n++ )); do out+=("$n"); done
                elif [[ "$part" =~ ^[0-9]+$ ]] && (( part >= 1 && part <= max )); then
                    out+=("$part")
                fi
            done
            printf '%s\n' "${out[@]}"
        }

        # Collect symlink decisions — no filesystem writes yet
        local do_symlinks=false
        local -a symlink_dirs=(Documents Pictures Videos Music Downloads Projects)
        local -a symlink_spicks=()
        # move_decisions: parallel array to symlink_spicks — "move" or "skip"
        local -a move_decisions=()
        local symlink_confirm
        {
            printf '\n'
            printf '  Would you like to create standard symlinks pointing into %s?\n' "$data_folder"
            printf '  e.g.  ~/Documents  ->  %s/Documents\n' "$data_folder"
            printf '        ~/Pictures   ->  %s/Pictures\n' "$data_folder"
            printf '\n'
        } > /dev/tty
        read -rp "  Create symlinks? [y/N]: " symlink_confirm < /dev/tty

        if [[ "${symlink_confirm,,}" == "y" ]]; then
            do_symlinks=true
            local scount=${#symlink_dirs[@]}
            {
                printf '\n  Select which symlinks to create.\n'
                printf '  Use commas and/or ranges, e.g.  1,2,3  or  1-6\n\n'
                local si=0
                for sd in "${symlink_dirs[@]}"; do
                    (( si++ )) || true
                    printf '  %-3s %s\n' "${si})" "${sd}"
                done
                printf '\n'
            } > /dev/tty

            local sraw
            while true; do
                read -rp "  Selection [1-${scount}]: " sraw < /dev/tty
                mapfile -t symlink_spicks < <(_st_parse_selection "$sraw" "$scount")
                (( ${#symlink_spicks[@]} > 0 )) && break
                printf '%sNo valid numbers found. Enter numbers 1-%d using commas or ranges.%s\n' \
                    "${RED:-}" "$scount" "${RESET:-}" > /dev/tty
            done

            # Identify which selected dirs already exist as real directories
            local -a existing_real=()
            for sp in "${symlink_spicks[@]}"; do
                local _lnk="$HOME/${symlink_dirs[$((sp - 1))]}"
                [[ -d "$_lnk" && ! -L "$_lnk" ]] && existing_real+=("$_lnk")
            done

            # Collect move/skip decisions for each existing real dir — no writes yet
            local move_all=false
            if (( ${#existing_real[@]} > 1 )); then
                {
                    printf '\n  %d existing directories will need their files moved:\n' "${#existing_real[@]}"
                    for _e in "${existing_real[@]}"; do printf '    • %s\n' "$_e"; done
                    printf '\n  Move all of them automatically, or confirm each one individually?\n\n'
                    printf '  1)  Yes to all  — move every existing directory\n'
                    printf '  2)  Confirm each individually\n\n'
                } > /dev/tty
                local bulk_choice
                read -rp "  Choice [1-2]: " bulk_choice < /dev/tty
                [[ "$bulk_choice" == "1" ]] && move_all=true
            fi

            for sp in "${symlink_spicks[@]}"; do
                local sdir="${symlink_dirs[$((sp - 1))]}"
                local lnk="$HOME/$sdir"
                if [[ -d "$lnk" && ! -L "$lnk" ]]; then
                    if [[ "$move_all" == "true" ]]; then
                        move_decisions+=("move")
                    else
                        {
                            printf '\n  %s exists and contains files.\n' "$lnk"
                            printf '  Move its contents into %s/%s and replace with a symlink?\n\n' \
                                "$data_folder" "$sdir"
                            printf '  1)  Move files then symlink  (recommended)\n'
                            printf '  2)  Skip this directory\n'
                            printf '  3)  Yes to all remaining\n\n'
                        } > /dev/tty
                        local move_choice
                        read -rp "  Choice [1-3]: " move_choice < /dev/tty
                        case "$move_choice" in
                            1) move_decisions+=("move") ;;
                            3) move_all=true; move_decisions+=("move") ;;
                            *) move_decisions+=("skip") ;;
                        esac
                    fi
                else
                    move_decisions+=("na")
                fi
            done
        fi

        # UID warning for distro-hopping (informational only — show before summary)
        {
            printf '\n'
            printf '  %s─── Distro-Hopping Tip ─────────────────────────────────────────%s\n' \
                "${BOLD:-}" "${RESET:-}"
            printf '\n'
            printf '  Different distros may assign different UIDs (e.g. 1000 vs 1001).\n'
            printf '  To avoid permission errors when switching distros:\n'
            printf '\n'
            printf '    1. Set your UID to 1000 during new installs.\n'
            printf '    2. If you encounter permission issues on an existing install:\n'
            printf '       sudo chown -R 1000:1000 %s\n' "$data_folder"
            printf '\n'
            printf '  On a new distro, add this folder in Syncthing as "Receive Only"\n'
            printf '  first, let it reconcile, then switch to "Send & Receive".\n'
            printf '\n'
        } > /dev/tty
    fi

    # ── Step 4: .stignore strategy (Strategy 1 only) ─────────────────────────
    local stignore_style=""
    if [[ "$strategy" == "1" ]] && (( ${#selected_folders[@]} > 0 )); then
        {
            printf '\n'
            printf '  Choose a .stignore style for your selected folders:\n\n'
            printf '  1)  Permissive  — minimal ignores, only a comment placeholder\n'
            printf '  2)  Restrictive — ignore *.tmp, *.swp, caches, node_modules, .git\n'
            printf '  3)  Skip        — do not create .stignore files\n\n'
        } > /dev/tty

        local ign_choice
        while true; do
            read -rp "  .stignore style [1-3]: " ign_choice < /dev/tty
            case "$ign_choice" in
                1) stignore_style="permissive";  break ;;
                2) stignore_style="restrictive"; break ;;
                3) stignore_style="skip";        break ;;
                *) printf '%sEnter 1, 2, or 3.%s\n' "${RED:-}" "${RESET:-}" > /dev/tty ;;
            esac
        done
    fi

    # ── Step 5: Dotfiles advice ───────────────────────────────────────────────
    local dotfiles_confirm
    read -rp "Would you like guidance on syncing dotfiles? [y/N]: " dotfiles_confirm < /dev/tty
    [[ "${dotfiles_confirm,,}" == "y" ]] && _st_dotfiles_info

    # ── Step 6: Firewall ──────────────────────────────────────────────────────
    local ufw_done=false
    if command -v ufw &>/dev/null && ufw status 2>/dev/null | grep -q "^Status: active"; then
        {
            printf '\n'
            printf '  UFW firewall is active. Syncthing needs:\n'
            printf '    22000/tcp  (sync traffic)\n'
            printf '    21027/udp  (local discovery)\n\n'
        } > /dev/tty
        local ufw_confirm
        read -rp "  Open these ports in UFW? [y/N]: " ufw_confirm < /dev/tty
        if [[ "${ufw_confirm,,}" == "y" ]]; then
            ufw_done=true
        fi
    fi

    # ── Step 7: Summary & confirmation ───────────────────────────────────────
    {
        printf '\n'
        printf '  %s─── Summary ────────────────────────────────────────────────────%s\n' \
            "${BOLD:-}" "${RESET:-}"
        printf '\n'
        printf '  Strategy:  %s\n' \
            "$( [[ "$strategy" == "1" ]] && echo "Sync specific subdirectories" \
                                        || echo "Dedicated data folder" )"
        printf '\n'
        printf '  Folders to configure in Syncthing:\n'
        for f in "${selected_folders[@]}"; do
            printf '    • %s\n' "$f"
        done
        if [[ "$strategy" == "1" && "$stignore_style" != "skip" && -n "$stignore_style" ]]; then
            printf '\n  .stignore style: %s\n' "$stignore_style"
        fi
        if [[ "$ufw_done" == "true" ]]; then
            printf '\n  UFW: will open 22000/tcp and 21027/udp\n'
        fi
        printf '\n'
        printf '  NOTE: This wizard only prepares your folder structure and\n'
        printf '  .stignore files. You must still add folders and remote devices\n'
        printf '  in the Syncthing web GUI: http://127.0.0.1:8384\n'
        printf '\n'
    } > /dev/tty

    local final_confirm
    read -rp "Proceed with the above? [y/N]: " final_confirm < /dev/tty
    if [[ "${final_confirm,,}" != "y" ]]; then
        info "Wizard cancelled — no changes made."
        return 0
    fi

    # ── Step 8a: Apply strategy 2 filesystem changes ─────────────────────────
    if [[ "$strategy" == "2" ]]; then
        if [[ "$create_data_folder" == "true" ]]; then
            if [[ "${DRY_RUN:-false}" == "true" ]]; then
                info "[Dry run] Would create directory: ${data_folder}"
            else
                mkdir -p "$data_folder" && info "Created: ${data_folder}"
            fi
        fi

        if [[ "$do_symlinks" == "true" ]]; then
            _st_do_move() {
                local src="$1" lnk="$2"
                mkdir -p "$src"
                if mv "$lnk"/. "$src"/ 2>/dev/null; then
                    rmdir "$lnk" 2>/dev/null || true
                else
                    cp -a "$lnk/." "$src/"
                    rm -rf "$lnk"
                fi
                ln -s "$src" "$lnk" && info "  Moved and symlinked: ${lnk} -> ${src}"
            }

            local _di=0
            for sp in "${symlink_spicks[@]}"; do
                local sdir="${symlink_dirs[$((sp - 1))]}"
                local src="$data_folder/$sdir"
                local lnk="$HOME/$sdir"
                local decision="${move_decisions[$_di]}"
                (( _di++ )) || true

                if [[ "${DRY_RUN:-false}" == "true" ]]; then
                    info "[Dry run] Would set up: ${lnk} -> ${src} (${decision})"
                    continue
                fi

                if [[ "$decision" == "move" ]]; then
                    _st_do_move "$src" "$lnk"
                elif [[ "$decision" == "skip" ]]; then
                    info "  Skipped: ${lnk}"
                elif [[ -L "$lnk" ]]; then
                    info "  Symlink already exists: ${lnk}"
                else
                    mkdir -p "$src"
                    ln -s "$src" "$lnk" && info "  Symlinked: ${lnk} -> ${src}"
                fi
            done
        fi
    fi

    # ── Step 8b: Apply .stignore files ───────────────────────────────────────
    if [[ "$strategy" == "1" && "$stignore_style" != "skip" && -n "$stignore_style" ]]; then
        for f in "${selected_folders[@]}"; do
            if [[ -d "$f" || "${DRY_RUN:-false}" == "true" ]]; then
                _st_write_stignore "$f" "$stignore_style"
            else
                warn "  Skipping .stignore for ${f} — directory does not exist."
            fi
        done
    fi

    # ── Step 9: Apply UFW rules ───────────────────────────────────────────────
    if [[ "$ufw_done" == "true" ]]; then
        if [[ "${DRY_RUN:-false}" == "true" ]]; then
            info "[Dry run] Would run: sudo ufw allow 22000/tcp"
            info "[Dry run] Would run: sudo ufw allow 21027/udp"
        else
            sudo ufw allow 22000/tcp && info "UFW: opened 22000/tcp"
            sudo ufw allow 21027/udp && info "UFW: opened 21027/udp"
        fi
    fi

    # ── Done ──────────────────────────────────────────────────────────────────
    {
        printf '\n'
        printf '  %s%sDone!%s\n' "${BOLD:-}" "${CYAN:-}" "${RESET:-}"
        printf '\n'
        printf '  Next steps:\n'
        printf '  1. Open the web GUI: http://127.0.0.1:8384\n'
        printf '  2. Add each folder above via "Add Folder"\n'
        printf '  3. Add your remote devices via "Add Device"\n'
        printf '  4. Enable "Watch for Changes" in each folder'\''s Advanced settings\n'
        printf '\n'
    } > /dev/tty

    return 0
}

# ── Lifecycle stubs ───────────────────────────────────────────────────────────
check_syncthing_folders()     { return 1; }
uninstall_syncthing_folders() { return 0; }
update_syncthing_folders()    { setup_syncthing_folders; }
get_version_syncthing_folders() { echo ""; }
