#!/bin/bash
# WireGuard Client installer functions

# --- WireGuard Client ---

readonly _WG_CLIENT_DIR="/etc/wireguard"
readonly _WG_CLIENT_IFACE="wg-client"

check_wireguard_client() {
    command -v wg &>/dev/null && {
        [[ -f "${_WG_CLIENT_DIR}/${_WG_CLIENT_IFACE}.conf" ]] || \
        nmcli -t connection show "${_WG_CLIENT_IFACE}" &>/dev/null
    }
}

install_wireguard_client() {
    info "Installing WireGuard Client..."
    ensure_tools

    # Detect whether NetworkManager is available (desktop environment GUI support)
    local use_nm=false
    if systemctl is-active --quiet NetworkManager 2>/dev/null; then
        use_nm=true
    fi

    # Install WireGuard packages
    case "$DISTRO_FAMILY" in
        debian)
            sudo apt update
            sudo apt install -y wireguard wireguard-tools
            if [[ "$use_nm" == true ]]; then
                sudo apt install -y network-manager 2>/dev/null || true
            fi
            ;;
        fedora|rhel)
            sudo "$PKG_MGR" install -y wireguard-tools
            if [[ "$use_nm" == true ]]; then
                sudo "$PKG_MGR" install -y NetworkManager 2>/dev/null || true
            fi
            ;;
        arch)
            sudo pacman -S --noconfirm wireguard-tools
            if [[ "$use_nm" == true ]]; then
                sudo pacman -S --noconfirm networkmanager 2>/dev/null || true
            fi
            ;;
        suse)
            sudo zypper install -y wireguard-tools
            if [[ "$use_nm" == true ]]; then
                sudo zypper install -y NetworkManager 2>/dev/null || true
            fi
            ;;
        *)
            error "Unsupported distribution family: $DISTRO_FAMILY"
            return 1
            ;;
    esac

    # Prompt for client configuration file
    echo ""
    info "A WireGuard configuration file (.conf) from your server is required."
    info "This is typically generated by the WireGuard Server installer or your VPN provider."
    echo ""

    local conf_path=""
    conf_path=$(_wg_client_prompt_config)
    # _wg_client_prompt_config returns empty string if user declined
    if [[ -z "$conf_path" ]]; then
        warn "No config imported. WireGuard is installed but not configured."
        return 0
    fi

    if [[ "$use_nm" == true ]]; then
        _wg_client_import_nm "$conf_path"
    else
        _wg_client_import_wgquick "$conf_path"
    fi

    info "WireGuard Client installed successfully."
}

# Prompt the user for a .conf file path with validation.
# Prints the validated path to stdout, or empty string if user gave up.
_wg_client_prompt_config() {
    local conf_path=""
    while true; do
        read -rp "Path to WireGuard client config file (.conf): " conf_path

        # Expand tilde
        conf_path="${conf_path/#\~/$HOME}"

        if [[ -z "$conf_path" ]]; then
            error "No path provided."
            while true; do
                read -rp "Try again? [Y/n]: " retry
                case "${retry,,}" in
                    y|yes|'') break ;;
                    n|no) echo ""; return 0 ;;
                    *) echo "  Please enter Y or N." ;;
                esac
            done
            continue
        fi

        if [[ ! -f "$conf_path" ]]; then
            error "File not found: $conf_path"
            while true; do
                read -rp "Try again? [Y/n]: " retry
                case "${retry,,}" in
                    y|yes|'') break ;;
                    n|no) echo ""; return 0 ;;
                    *) echo "  Please enter Y or N." ;;
                esac
            done
            continue
        fi

        if [[ "${conf_path##*.}" != "conf" ]]; then
            warn "File does not have a .conf extension. Continuing anyway."
        fi

        # Validate the config has required sections
        if ! grep -qE '^\[Interface\]' "$conf_path" 2>/dev/null; then
            error "File does not appear to be a valid WireGuard config (missing [Interface] section)."
            while true; do
                read -rp "Try again? [Y/n]: " retry
                case "${retry,,}" in
                    y|yes|'') break ;;
                    n|no) echo ""; return 0 ;;
                    *) echo "  Please enter Y or N." ;;
                esac
            done
            continue
        fi

        echo "$conf_path"
        return 0
    done
}

# Import config via NetworkManager (GUI-friendly — shows in GNOME/KDE network settings)
_wg_client_import_nm() {
    local conf_path="$1"
    local conn_name="${_WG_CLIENT_IFACE}"

    # Remove any existing NM connection with the same name
    nmcli connection delete "$conn_name" 2>/dev/null || true

    info "Importing config into NetworkManager..."
    if ! nmcli connection import type wireguard file "$conf_path"; then
        error "NetworkManager import failed. Falling back to wg-quick."
        _wg_client_import_wgquick "$conf_path"
        return
    fi

    # nmcli names the connection after the filename; rename to our standard name
    local imported_name
    imported_name=$(basename "$conf_path" .conf)
    if [[ "$imported_name" != "$conn_name" ]]; then
        nmcli connection modify "$imported_name" connection.id "$conn_name" 2>/dev/null || true
    fi

    info "WireGuard connection added to NetworkManager as '${conn_name}'."
    info "You can manage it from your desktop network settings or with:"
    info "  nmcli connection up ${conn_name}"
    info "  nmcli connection down ${conn_name}"

    # Also save a copy under /etc/wireguard for the check function
    sudo mkdir -p "$_WG_CLIENT_DIR"
    sudo cp "$conf_path" "${_WG_CLIENT_DIR}/${_WG_CLIENT_IFACE}.conf"
    sudo chmod 600 "${_WG_CLIENT_DIR}/${_WG_CLIENT_IFACE}.conf"

    echo ""
    while true; do
        read -rp "Activate the VPN connection now? [Y/n]: " activate
        activate="${activate:-Y}"
        case "${activate,,}" in
            y|yes)
                nmcli connection up "$conn_name"
                info "WireGuard tunnel is active."
                break
                ;;
            n|no) break ;;
            *) echo "  Please enter Y or N." ;;
        esac
    done
}

# Import config via wg-quick (headless / no desktop environment)
_wg_client_import_wgquick() {
    local conf_path="$1"

    sudo mkdir -p "$_WG_CLIENT_DIR"
    sudo cp "$conf_path" "${_WG_CLIENT_DIR}/${_WG_CLIENT_IFACE}.conf"
    sudo chmod 600 "${_WG_CLIENT_DIR}/${_WG_CLIENT_IFACE}.conf"
    sudo chown root:root "${_WG_CLIENT_DIR}/${_WG_CLIENT_IFACE}.conf"

    info "Config imported to ${_WG_CLIENT_DIR}/${_WG_CLIENT_IFACE}.conf"

    echo ""
    while true; do
        read -rp "Start WireGuard tunnel now and enable on boot? [Y/n]: " start_now
        start_now="${start_now:-Y}"
        case "${start_now,,}" in
            y|yes)
                sudo systemctl enable "wg-quick@${_WG_CLIENT_IFACE}"
                sudo systemctl start "wg-quick@${_WG_CLIENT_IFACE}"
                info "WireGuard tunnel is active."
                sudo wg show "$_WG_CLIENT_IFACE" 2>/dev/null || true
                break
                ;;
            n|no)
                info "To start the tunnel manually: sudo wg-quick up ${_WG_CLIENT_IFACE}"
                info "To enable on boot: sudo systemctl enable wg-quick@${_WG_CLIENT_IFACE}"
                break
                ;;
            *) echo "  Please enter Y or N." ;;
        esac
    done
}

uninstall_wireguard_client() {
    info "Uninstalling WireGuard Client..."

    # Remove NetworkManager connection if it exists
    nmcli connection delete "${_WG_CLIENT_IFACE}" 2>/dev/null || true

    # Stop and disable the wg-quick tunnel
    sudo systemctl stop "wg-quick@${_WG_CLIENT_IFACE}" 2>/dev/null || true
    sudo systemctl disable "wg-quick@${_WG_CLIENT_IFACE}" 2>/dev/null || true

    # Remove client configuration
    sudo rm -f "${_WG_CLIENT_DIR}/${_WG_CLIENT_IFACE}.conf"

    # Only remove packages if no other WireGuard configs remain
    local remaining_confs
    remaining_confs=$(find "$_WG_CLIENT_DIR" -name '*.conf' 2>/dev/null | wc -l)
    if (( remaining_confs == 0 )); then
        case "$DISTRO_FAMILY" in
            debian)
                sudo apt purge --autoremove -y wireguard wireguard-tools 2>/dev/null || true
                ;;
            fedora|rhel)
                sudo "$PKG_MGR" remove -y wireguard-tools 2>/dev/null || true
                ;;
            arch)
                sudo pacman -Rs --noconfirm wireguard-tools 2>/dev/null || true
                ;;
            suse)
                sudo zypper remove -y wireguard-tools 2>/dev/null || true
                ;;
        esac
        sudo rmdir "$_WG_CLIENT_DIR" 2>/dev/null || true
    else
        info "Other WireGuard configs exist — keeping packages installed."
    fi

    info "WireGuard Client uninstalled."
}

update_wireguard_client() {
    info "Updating WireGuard Client..."
    case "$DISTRO_FAMILY" in
        debian)  sudo apt-get install -y --only-upgrade wireguard wireguard-tools ;;
        fedora|rhel) sudo "$PKG_MGR" upgrade -y wireguard-tools ;;
        arch)    sudo pacman -S --noconfirm wireguard-tools ;;
        suse)    sudo zypper update -y wireguard-tools ;;
    esac
}

get_version_wireguard_client() {
    wg --version 2>/dev/null | grep -oP 'wireguard-tools v\K[\d.]+' || echo ""
}
